In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import math

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/diabetes.csv")

In [ ]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
#dataset dimensional no of rows and colunms
df.shape

(768, 9)

In [ ]:
#fist 5records
df.head(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
#last 5records
df.tail(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
#number of missing values in each column
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
#statistical methods
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
a = list(df.Glucose)
print(a)

[148, 85, 183, 89, 137, 116, 78, 115, 197, 125, 110, 168, 139, 189, 166, 100, 118, 107, 103, 115, 126, 99, 196, 119, 143, 125, 147, 97, 145, 117, 109, 158, 88, 92, 122, 103, 138, 102, 90, 111, 180, 133, 106, 171, 159, 180, 146, 71, 103, 105, 103, 101, 88, 176, 150, 73, 187, 100, 146, 105, 84, 133, 44, 141, 114, 99, 109, 109, 95, 146, 100, 139, 126, 129, 79, 0, 62, 95, 131, 112, 113, 74, 83, 101, 137, 110, 106, 100, 136, 107, 80, 123, 81, 134, 142, 144, 92, 71, 93, 122, 163, 151, 125, 81, 85, 126, 96, 144, 83, 95, 171, 155, 89, 76, 160, 146, 124, 78, 97, 99, 162, 111, 107, 132, 113, 88, 120, 118, 117, 105, 173, 122, 170, 84, 96, 125, 100, 93, 129, 105, 128, 106, 108, 108, 154, 102, 57, 106, 147, 90, 136, 114, 156, 153, 188, 152, 99, 109, 88, 163, 151, 102, 114, 100, 131, 104, 148, 120, 110, 111, 102, 134, 87, 79, 75, 179, 85, 129, 143, 130, 87, 119, 0, 73, 141, 194, 181, 128, 109, 139, 111, 123, 159, 135, 85, 158, 105, 107, 109, 148, 113, 138, 108, 99, 103, 111, 196, 162, 96, 184, 81, 147, 179, 140, 112, 151, 109, 125, 85, 112, 177, 158, 119, 142, 100, 87, 101, 162, 197, 117, 142, 134, 79, 122, 74, 171, 181, 179, 164, 104, 91, 91, 139, 119, 146, 184, 122, 165, 124, 111, 106, 129, 90, 86, 92, 113, 111, 114, 193, 155, 191, 141, 95, 142, 123, 96, 138, 128, 102, 146, 101, 108, 122, 71, 106, 100, 106, 104, 114, 108, 146, 129, 133, 161, 108, 136, 155, 119, 96, 108, 78, 107, 128, 128, 161, 151, 146, 126, 100, 112, 167, 144, 77, 115, 150, 120, 161, 137, 128, 124, 80, 106, 155, 113, 109, 112, 99, 182, 115, 194, 129, 112, 124, 152, 112, 157, 122, 179, 102, 105, 118, 87, 180, 106, 95, 165, 117, 115, 152, 178, 130, 95, 0, 122, 95, 126, 139, 116, 99, 0, 92, 137, 61, 90, 90, 165, 125, 129, 88, 196, 189, 158, 103, 146, 147, 99, 124, 101, 81, 133, 173, 118, 84, 105, 122, 140, 98, 87, 156, 93, 107, 105, 109, 90, 125, 119, 116, 105, 144, 100, 100, 166, 131, 116, 158, 127, 96, 131, 82, 193, 95, 137, 136, 72, 168, 123, 115, 101, 197, 172, 102, 112, 143, 143, 138, 173, 97, 144, 83, 129, 119, 94, 102, 115, 151, 184, 94, 181, 135, 95, 99, 89, 80, 139, 90, 141, 140, 147, 97, 107, 189, 83, 117, 108, 117, 180, 100, 95, 104, 120, 82, 134, 91, 119, 100, 175, 135, 86, 148, 134, 120, 71, 74, 88, 115, 124, 74, 97, 120, 154, 144, 137, 119, 136, 114, 137, 105, 114, 126, 132, 158, 123, 85, 84, 145, 135, 139, 173, 99, 194, 83, 89, 99, 125, 80, 166, 110, 81, 195, 154, 117, 84, 0, 94, 96, 75, 180, 130, 84, 120, 84, 139, 91, 91, 99, 163, 145, 125, 76, 129, 68, 124, 114, 130, 125, 87, 97, 116, 117, 111, 122, 107, 86, 91, 77, 132, 105, 57, 127, 129, 100, 128, 90, 84, 88, 186, 187, 131, 164, 189, 116, 84, 114, 88, 84, 124, 97, 110, 103, 85, 125, 198, 87, 99, 91, 95, 99, 92, 154, 121, 78, 130, 111, 98, 143, 119, 108, 118, 133, 197, 151, 109, 121, 100, 124, 93, 143, 103, 176, 73, 111, 112, 132, 82, 123, 188, 67, 89, 173, 109, 108, 96, 124, 150, 183, 124, 181, 92, 152, 111, 106, 174, 168, 105, 138, 106, 117, 68, 112, 119, 112, 92, 183, 94, 108, 90, 125, 132, 128, 94, 114, 102, 111, 128, 92, 104, 104, 94, 97, 100, 102, 128, 147, 90, 103, 157, 167, 179, 136, 107, 91, 117, 123, 120, 106, 155, 101, 120, 127, 80, 162, 199, 167, 145, 115, 112, 145, 111, 98, 154, 165, 99, 68, 123, 91, 195, 156, 93, 121, 101, 56, 162, 95, 125, 136, 129, 130, 107, 140, 144, 107, 158, 121, 129, 90, 142, 169, 99, 127, 118, 122, 125, 168, 129, 110, 80, 115, 127, 164, 93, 158, 126, 129, 134, 102, 187, 173, 94, 108, 97, 83, 114, 149, 117, 111, 112, 116, 141, 175, 92, 130, 120, 174, 106, 105, 95, 126, 65, 99, 102, 120, 102, 109, 140, 153, 100, 147, 81, 187, 162, 136, 121, 108, 181, 154, 128, 137, 123, 106, 190, 88, 170, 89, 101, 122, 121, 126, 93]

In [ ]:
b = list(df.BloodPressure)
print(b)

[72, 66, 64, 66, 40, 74, 50, 0, 70, 96, 92, 74, 80, 60, 72, 0, 84, 74, 30, 70, 88, 84, 90, 80, 94, 70, 76, 66, 82, 92, 75, 76, 58, 92, 78, 60, 76, 76, 68, 72, 64, 84, 92, 110, 64, 66, 56, 70, 66, 0, 80, 50, 66, 90, 66, 50, 68, 88, 82, 64, 0, 72, 62, 58, 66, 74, 88, 92, 66, 85, 66, 64, 90, 86, 75, 48, 78, 72, 0, 66, 44, 0, 78, 65, 108, 74, 72, 68, 70, 68, 55, 80, 78, 72, 82, 72, 62, 48, 50, 90, 72, 60, 96, 72, 65, 56, 122, 58, 58, 85, 72, 62, 76, 62, 54, 92, 74, 48, 60, 76, 76, 64, 74, 80, 76, 30, 70, 58, 88, 84, 70, 56, 64, 74, 68, 60, 70, 60, 80, 72, 78, 82, 52, 66, 62, 75, 80, 64, 78, 70, 74, 65, 86, 82, 78, 88, 52, 56, 74, 72, 90, 74, 80, 64, 88, 74, 66, 68, 66, 90, 82, 70, 0, 60, 64, 72, 78, 110, 78, 82, 80, 64, 74, 60, 74, 68, 68, 98, 76, 80, 62, 70, 66, 0, 55, 84, 58, 62, 64, 60, 80, 82, 68, 70, 72, 72, 76, 104, 64, 84, 60, 85, 95, 65, 82, 70, 62, 68, 74, 66, 60, 90, 0, 60, 66, 78, 76, 52, 70, 80, 86, 80, 80, 68, 68, 72, 84, 90, 84, 76, 64, 70, 54, 50, 76, 85, 68, 90, 70, 86, 52, 84, 80, 68, 62, 64, 56, 68, 50, 76, 68, 0, 70, 80, 62, 74, 0, 64, 52, 0, 86, 62, 78, 78, 70, 70, 60, 64, 74, 62, 70, 76, 88, 86, 80, 74, 84, 86, 56, 72, 88, 62, 78, 48, 50, 62, 70, 84, 78, 72, 0, 58, 82, 98, 76, 76, 68, 68, 68, 68, 66, 70, 74, 50, 80, 68, 80, 74, 66, 78, 60, 74, 70, 90, 75, 72, 64, 70, 86, 70, 72, 58, 0, 80, 60, 76, 0, 76, 78, 84, 70, 74, 68, 86, 72, 88, 46, 0, 62, 80, 80, 84, 82, 62, 78, 88, 50, 0, 74, 76, 64, 70, 108, 78, 74, 54, 72, 64, 86, 102, 82, 64, 64, 58, 52, 82, 82, 60, 75, 100, 72, 68, 60, 62, 70, 54, 74, 100, 82, 68, 66, 76, 64, 72, 78, 58, 56, 66, 70, 70, 64, 61, 84, 78, 64, 48, 72, 62, 74, 68, 90, 72, 84, 74, 60, 84, 68, 82, 68, 64, 88, 68, 64, 64, 78, 78, 0, 64, 94, 82, 0, 74, 74, 75, 68, 0, 85, 75, 70, 88, 104, 66, 64, 70, 62, 78, 72, 80, 64, 74, 64, 70, 68, 0, 54, 62, 54, 68, 84, 74, 72, 62, 70, 78, 98, 56, 52, 64, 0, 78, 82, 70, 66, 90, 64, 84, 80, 76, 74, 86, 70, 88, 58, 82, 0, 68, 62, 78, 72, 80, 65, 90, 68, 70, 0, 74, 68, 72, 70, 74, 90, 72, 68, 64, 78, 82, 90, 60, 50, 78, 72, 62, 68, 62, 54, 70, 88, 86, 60, 90, 70, 80, 0, 70, 58, 60, 64, 74, 66, 65, 60, 76, 66, 0, 56, 0, 90, 60, 80, 92, 74, 72, 85, 90, 78, 90, 76, 68, 82, 110, 70, 68, 88, 62, 64, 70, 70, 76, 68, 74, 76, 66, 68, 60, 80, 54, 72, 62, 72, 66, 70, 96, 58, 60, 86, 44, 44, 80, 68, 70, 90, 60, 78, 76, 76, 56, 66, 66, 86, 0, 84, 78, 80, 52, 72, 82, 76, 24, 74, 38, 88, 0, 74, 78, 0, 60, 78, 62, 82, 62, 54, 58, 88, 80, 74, 72, 96, 62, 82, 0, 86, 76, 94, 70, 64, 88, 68, 78, 80, 65, 64, 78, 60, 82, 62, 72, 74, 76, 76, 74, 86, 70, 80, 0, 72, 74, 74, 50, 84, 60, 54, 60, 74, 54, 70, 52, 58, 80, 106, 82, 84, 76, 106, 80, 60, 80, 82, 70, 58, 78, 68, 58, 106, 100, 82, 70, 86, 60, 52, 58, 56, 76, 64, 80, 82, 74, 64, 50, 74, 82, 80, 114, 70, 68, 60, 90, 74, 0, 88, 70, 76, 78, 88, 0, 76, 80, 0, 46, 78, 64, 64, 78, 62, 58, 74, 50, 78, 72, 60, 76, 86, 66, 68, 86, 94, 78, 78, 84, 88, 52, 78, 86, 88, 56, 75, 60, 86, 72, 60, 74, 80, 44, 58, 94, 88, 84, 94, 74, 70, 62, 70, 78, 62, 88, 78, 88, 90, 72, 76, 92, 58, 74, 62, 76, 70, 72, 60, 70]

In [ ]:
c = list(df.Outcome)
print(c)
count = len(c)

[1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0]

In [ ]:
nx=148
ny=72
#ny=float(y)
ans=[]
e=[]
for i in range(0, count):
  ans.append(math.sqrt(((nx-a[i])*(nx-a[i]))+((ny-b[i])*(ny-b[i]))))
print(ans)
#d=ans.index(min(ans))
#print('Index=',d)
#print('class label=',c[d])
#cd=c[d]
e=sorted(ans)
k=int(input("Enter k value:"))
cc=[]

for x in range(0,k):
  sd=ans.index(e[x])
  cc.append(c[sd])

print("K list:",cc)

[0.0, 63.28506932918696, 35.90264614203248, 59.30430001273095, 33.83784863137726, 32.0624390837628, 73.37574531137656, 79.20227269466452, 49.040799340956916, 33.24154027718932, 42.941821107167776, 20.09975124224178, 12.041594578792296, 42.720018726587654, 18.0, 86.53323061113575, 32.31098884280702, 41.048751503547585, 61.554853586049575, 33.06055050963308, 27.202941017470888, 50.44799302251776, 51.264022471905186, 30.083217912982647, 22.561028345356956, 23.08679276123039, 4.123105625617661, 51.35172830587107, 10.44030650891055, 36.89173349139343, 39.11521443121589, 10.770329614269007, 61.61168720299745, 59.464274989274024, 26.68332812825267, 46.57252408878007, 10.770329614269007, 46.17358552246078, 58.137767414994535, 37.0, 32.984845004941285, 19.209372712298546, 46.51881339845203, 44.41846462902562, 13.601470508735444, 32.55764119219941, 16.1245154965971, 77.02596964660685, 45.39823785126467, 83.86298349093002, 45.70557952810576, 51.894122981316485, 60.29925372672534, 33.28663395418648, 6.324555320336759, 78.16009211867653, 39.20459156782532, 50.59644256269407, 10.198039027185569, 43.73785545725808, 96.33275663033837, 15.0, 104.47966309287182, 15.652475842498529, 34.52535300326414, 49.040799340956916, 42.15447781671598, 43.829214001622255, 53.33854141237835, 13.152946437965905, 48.373546489791295, 12.041594578792296, 28.42534080710379, 23.600847442411894, 69.06518659932803, 149.9333185119305, 86.20904824900923, 53.0, 73.97972695272672, 36.49657518178932, 44.82186966202994, 103.24727599312246, 65.27633568147036, 47.51841748206689, 37.64306044943742, 38.05259518088089, 42.0, 48.16637831516918, 12.165525060596439, 41.19465984809196, 70.09279563550022, 26.248809496813376, 67.26812023536856, 14.0, 11.661903789690601, 4.0, 56.88585061331157, 80.65358020571685, 59.23681287847955, 31.622776601683793, 15.0, 12.36931687685298, 33.24154027718932, 67.0, 63.387695966961914, 27.202941017470888, 72.13875518748573, 14.560219778561036, 66.49060083951716, 54.57105459856901, 23.0, 12.206555615733702, 59.135437767890075, 72.69112738154499, 21.633307652783937, 20.09975124224178, 24.08318915758459, 74.0, 52.392747589718944, 49.16299421312742, 14.560219778561036, 37.8549864614954, 41.048751503547585, 17.88854381999832, 35.22782990761707, 73.23933369440222, 28.071337695236398, 33.1058907144937, 34.88552708502482, 44.64302857109943, 25.079872407968907, 30.528675044947494, 23.40939982143925, 64.03124237432849, 52.15361924162119, 25.942243542145693, 48.041648597857254, 56.293871780150276, 20.615528128088304, 43.0, 20.8806130178211, 43.174066289845804, 44.721359549995796, 40.44749683231337, 11.661903789690601, 46.09772228646444, 91.35097153287424, 42.7551166528639, 6.082762530298219, 58.034472514187634, 12.165525060596439, 34.713109915419565, 16.1245154965971, 11.180339887498949, 40.44749683231337, 16.492422502470642, 52.92447448959697, 42.15447781671598, 60.03332407921454, 15.0, 18.24828759089466, 46.04345773288535, 34.92849839314596, 48.662100242385755, 23.345235059857504, 44.04543109109048, 6.0, 28.284271247461902, 38.47076812334269, 41.14608122288197, 47.07440918375928, 14.142135623730951, 94.36630754670864, 70.03570517957252, 73.43704787094863, 31.0, 63.28506932918696, 42.485291572496, 7.810249675906654, 20.591260281974, 61.5223536610881, 30.083217912982647, 148.0135128966271, 75.95393340703298, 7.280109889280518, 46.17358552246078, 33.24154027718932, 32.802438933713454, 39.20459156782532, 12.041594578792296, 38.3275357934736, 25.079872407968907, 12.529964086141668, 73.16419889536138, 65.25335240430181, 15.620499351813308, 45.221676218380054, 42.20189569201838, 39.81205847478876, 12.0, 35.90264614203248, 14.142135623730951, 40.19950248448356, 49.040799340956916, 45.0, 37.0, 48.16637831516918, 34.92849839314596, 52.61178575186362, 37.94733192202055, 68.06614430096654, 13.038404810405298, 38.600518131237564, 10.63014581273465, 37.36308338453881, 3.605551275463989, 40.26164427839479, 23.345235059857504, 63.0317380372777, 36.49657518178932, 31.38470965295043, 20.591260281974, 77.62087348130012, 13.416407864998739, 48.373546489791295, 61.29437168288782, 47.16990566028302, 24.413111231467404, 49.040799340956916, 32.01562118716424, 15.231546211727817, 16.1245154965971, 69.46221994724903, 26.30589287593181, 74.10802925459562, 23.0, 35.11409973215888, 35.84689665786984, 20.0, 44.181444068749045, 57.55866572463264, 57.0350769263968, 20.12461179749811, 36.40054944640259, 4.47213595499958, 38.27531841800928, 26.30589287593181, 24.758836806279895, 24.08318915758459, 39.56008088970496, 46.51881339845203, 22.47220505424423, 58.54912467321779, 62.12889826803627, 56.88585061331157, 35.90264614203248, 40.311288741492746, 34.23448553724738, 50.08991914547278, 8.06225774829855, 43.18564576337837, 72.3394774656273, 53.03772242470448, 10.0, 26.92582403567252, 52.03844732503075, 72.69112738154499, 21.540659228538015, 50.15974481593781, 72.02777242147643, 49.040799340956916, 41.23105625617661, 26.68332812825267, 77.23341245859851, 42.04759208325728, 48.041648597857254, 43.68065933568311, 44.721359549995796, 34.058772731852805, 41.23105625617661, 2.8284271247461903, 19.4164878389476, 21.93171219946131, 19.1049731745428, 40.792156108742276, 12.165525060596439, 13.892443989449804, 32.202484376209235, 54.405882034941776, 40.0, 71.80529228406496, 42.20189569201838, 20.8806130178211, 31.240998703626616, 25.553864678361276, 10.44030650891055, 2.8284271247461903, 25.059928172283335, 48.373546489791295, 36.0, 74.46475676452586, 14.560219778561036, 71.7007670809734, 42.01190307520001, 4.47213595499958, 28.284271247461902, 13.601470508735444, 11.704699910719626, 20.396078054371138, 24.331050121192877, 68.26419266350405, 42.04759208325728, 7.280109889280518, 41.340053217188775, 39.81205847478876, 36.22154055254967, 49.64876634922564, 34.058772731852805, 33.54101966249684, 46.389654018972806, 22.47220505424423, 36.05551275463989, 24.08318915758459, 18.439088914585774, 36.124783736376884, 9.0, 27.202941017470888, 31.064449134018133, 48.08326112068523, 43.04648650006177, 30.0, 62.5859409132754, 78.79086241436883, 42.7551166528639, 54.3415126767741, 17.46424919657298, 78.39005038906404, 33.24154027718932, 7.211102550927978, 32.31098884280702, 18.110770276274835, 53.03772242470448, 148.05404418657398, 29.5296461204668, 53.0, 27.202941017470888, 27.51363298439521, 78.79086241436883, 50.00999900019995, 148.21605850919124, 56.568542494923804, 16.278820596099706, 87.5728268357257, 58.855755878248644, 58.309518948453004, 23.345235059857504, 31.827660925679098, 74.46475676452586, 60.03332407921454, 48.16637831516918, 41.773197148410844, 10.198039027185569, 57.62811813689564, 6.324555320336759, 2.23606797749979, 52.20153254455275, 24.0, 47.67598976424087, 68.4470598345904, 33.54101966249684, 26.92582403567252, 31.04834939252005, 64.4980619863884, 45.221676218380054, 32.802438933713454, 12.806248474865697, 50.99019513592785, 62.16912416947821, 8.54400374531753, 61.71709649683789, 41.0, 43.18564576337837, 40.80441152620633, 58.855755878248644, 23.08679276123039, 34.132096331752024, 32.0624390837628, 51.31276644267, 10.770329614269007, 48.16637831516918, 48.373546489791295, 18.439088914585774, 18.788294228055936, 32.0, 11.661903789690601, 25.238858928247925, 54.405882034941776, 18.027756377319946, 66.03029607687671, 45.044422518220834, 53.600373133029585, 15.556349186104045, 16.97056274847714, 76.23647421018367, 21.540659228538015, 34.655446902326915, 33.0, 48.05205510693585, 49.040799340956916, 24.331050121192877, 49.39635614091387, 36.0, 13.0, 5.385164807134504, 15.620499351813308, 27.730849247724095, 51.15662224971465, 10.770329614269007, 65.12296062065974, 20.615528128088304, 33.12099032335839, 54.147945482723536, 46.69047011971501, 33.95585369269929, 6.708203932499369, 36.49657518178932, 90.0, 33.95585369269929, 25.553864678361276, 53.9351462406472, 87.09190547921202, 59.033888572581766, 68.0294054067798, 9.486832980505138, 58.137767414994535, 72.3394774656273, 15.264337522473747, 3.1622776601683795, 51.03920062069938, 44.01136216933077, 52.009614495783374, 65.27633568147036, 32.01562118716424, 40.049968789001575, 32.57299494980466, 32.55764119219941, 48.0, 53.600373133029585, 44.721359549995796, 28.071337695236398, 66.48308055437865, 14.142135623730951, 57.14017850864661, 77.62087348130012, 51.264022471905186, 28.792360097775937, 22.20360331117452, 62.12889826803627, 12.0, 14.142135623730951, 28.0, 77.64663547121665, 74.02702209328699, 60.29925372672534, 42.01190307520001, 28.844410203711913, 76.6550715869472, 51.62363799656123, 77.25283166331187, 8.48528137423857, 10.770329614269007, 11.180339887498949, 29.614185789921695, 21.633307652783937, 34.92849839314596, 16.278820596099706, 43.73785545725808, 34.23448553724738, 22.090722034374522, 21.2602916254693, 10.198039027185569, 29.68164415931166, 64.53681120105021, 64.77653896280658, 72.06247289678588, 13.601470508735444, 13.45362404707371, 25.709920264364882, 49.0, 46.69047011971501, 65.37583651472461, 61.68468205316454, 49.16299421312742, 23.08679276123039, 99.03534722511958, 18.110770276274835, 38.2099463490856, 67.0, 47.042533945356304, 6.324555320336759, 35.84689665786984, 64.0, 148.05404418657398, 54.589376255824725, 52.3450093132096, 73.68174807915459, 36.71511950137164, 21.633307652783937, 67.67569726275453, 28.635642126552707, 64.0, 13.45362404707371, 57.14017850864661, 57.87054518492115, 52.20153254455275, 15.132745950421556, 16.278820596099706, 26.92582403567252, 72.99315036357864, 26.1725046566048, 80.02499609497022, 25.298221281347036, 79.62411694957753, 18.110770276274835, 26.92582403567252, 62.16912416947821, 51.62363799656123, 32.0624390837628, 31.575306807693888, 37.656340767525464, 28.635642126552707, 41.19465984809196, 62.289646009589745, 91.8313671900838, 72.78049189171504, 73.7563556583431, 46.61544808322666, 91.7877987534291, 22.47220505424423, 27.586228448267445, 48.041648597857254, 20.0, 59.43904440685432, 66.48308055437865, 60.29925372672534, 42.04759208325728, 39.20459156782532, 17.46424919657298, 18.867962264113206, 55.90169943749474, 32.0624390837628, 64.1248781675256, 37.57658845611187, 60.8276253029822, 64.4980619863884, 24.08318915758459, 51.03920062069938, 38.2099463490856, 45.17742799230607, 63.0317380372777, 23.345235059857504, 50.35871324805669, 61.1310068623117, 50.44799302251776, 57.55866572463264, 55.97320787662612, 49.0, 56.88585061331157, 6.0, 27.65863337187866, 70.02856560004639, 30.0, 39.56008088970496, 51.419840528729765, 14.866068747318506, 40.311288741492746, 48.82622246293481, 31.04834939252005, 15.524174696260024, 49.040799340956916, 18.24828759089466, 40.80441152620633, 27.65863337187866, 48.16637831516918, 24.331050121192877, 57.28001396647874, 7.810249675906654, 45.39823785126467, 31.304951684997057, 103.96634070698074, 38.897300677553446, 36.49657518178932, 17.88854381999832, 68.96375859826666, 25.0, 41.23105625617661, 81.09870529176159, 76.05918747922567, 25.079872407968907, 51.73973328110612, 43.08131845707603, 88.81441324469807, 24.08318915758459, 6.324555320336759, 80.05623023850174, 26.832815729997478, 33.54101966249684, 56.88585061331157, 10.770329614269007, 38.3275357934736, 45.69463863518345, 29.5296461204668, 25.612496949731394, 43.73785545725808, 10.198039027185569, 42.0, 39.20459156782532, 80.62257748298549, 37.36308338453881, 77.62087348130012, 38.62641583165593, 56.142675390472796, 41.340053217188775, 54.037024344425184, 40.792156108742276, 60.166435825965294, 23.345235059857504, 17.08800749063506, 21.540659228538015, 54.45181356024793, 34.92849839314596, 46.389654018972806, 38.897300677553446, 22.360679774997898, 56.88585061331157, 44.0, 44.04543109109048, 54.147945482723536, 51.15662224971465, 48.041648597857254, 48.08326112068523, 20.09975124224178, 8.06225774829855, 92.45539465060976, 45.0, 9.219544457292887, 19.1049731745428, 38.01315561749642, 16.97056274847714, 42.720018726587654, 59.77457653551382, 33.24154027718932, 25.079872407968907, 33.28663395418648, 42.04759208325728, 21.18962010041709, 49.040799340956916, 29.120439557122072, 39.96248240537617, 68.73136110975832, 18.439088914585774, 51.15662224971465, 38.948684188300895, 8.54400374531753, 35.11409973215888, 36.87817782917155, 10.44030650891055, 37.05401462729781, 51.92301994298868, 8.48528137423857, 17.46424919657298, 50.96076922496363, 86.92525524840292, 37.53664875824692, 57.87054518492115, 47.042533945356304, 16.1245154965971, 56.293871780150276, 33.60059523282288, 49.040799340956916, 93.38094023943002, 14.560219778561036, 53.600373133029585, 24.351591323771842, 15.620499351813308, 19.1049731745428, 19.697715603592208, 46.52956049652737, 8.246211251235321, 10.770329614269007, 41.773197148410844, 43.174066289845804, 27.073972741361768, 19.4164878389476, 59.22837157984339, 18.973665961010276, 21.095023109728988, 87.09190547921202, 26.40075756488817, 30.066592756745816, 26.30589287593181, 23.769728648009426, 25.612496949731394, 74.46475676452586, 38.2099463490856, 68.46897107449476, 79.20227269466452, 33.421549934136806, 17.08800749063506, 55.57877292636101, 12.806248474865697, 22.80350850198276, 21.470910553583888, 19.79898987322333, 46.04345773288535, 44.77722635447622, 25.709920264364882, 54.0, 41.7612260356422, 51.15662224971465, 66.49060083951716, 34.52535300326414, 4.123105625617661, 34.0147027033899, 43.04648650006177, 36.49657518178932, 32.55764119219941, 13.892443989449804, 31.38470965295043, 59.464274989274024, 18.973665961010276, 31.304951684997057, 30.528675044947494, 44.94441010848846, 43.104524124504614, 54.3415126767741, 26.076809620810597, 83.0, 50.44799302251776, 46.04345773288535, 29.120439557122072, 53.85164807134504, 41.43669871020132, 23.40939982143925, 16.76305461424021, 49.47726750741192, 22.02271554554524, 67.02984409947557, 39.05124837953327, 17.204650534085253, 12.165525060596439, 27.65863337187866, 41.23105625617661, 36.6742416417845, 8.48528137423857, 25.612496949731394, 21.095023109728988, 25.0, 42.190046219457976, 46.51881339845203, 61.61168720299745, 22.090722034374522, 59.841457201508724, 47.16990566028302, 26.076809620810597, 27.0, 25.059928172283335, 55.036351623268054]
Enter k value:7
K list: [1, 0, 1, 1, 0, 1, 0]

In [ ]:
def most_frequent(List):
    return max(set(List), key = List.count)

print("Class label :",most_frequent(cc))

Class label : 1